### ISSUE TITLE
Adapting for other test tools and frameworks!

### ISSUE THREAD

**Issue by nedwardsOF** [testable/openfin-wdio-testable-example#2]
Hi Avi. Thanks for putting this together!

I'm wondering if you've set up anything similar with other test tools and frameworks? I'm looking into working with several that are a little more modern than WebDriver, but noticing that many of them expect to launch the browser in a special / opinionated context, and not sure if they're a good fit for testing OpenFin apps on top of the OpenFin runtime and its executable.

If I use a tool that doesn't rely on the WebDriver protocol, I'm thinking I can get rid of the complex launch flow. I see you're using WebDriver's `onWorkerStart` hook to spawn a Node child process that opens the batch, passes through config and debugging port arguments, and then opens the RVM exe.
How does that make it over to the `test.js` file, so that the `browser` object is all ready to go and hooked into the running app?

I'm trying to determine how much of that flow I'll need to keep in mind with new tools, and whether they'd even support it. Playwright, Cypress, Taiko, and Puppeteer are on my list right now.

**Comment by avistramer** [comment]
Hi Nicholas - We're just finalizing our support for Puppeteer on Testable and as part of that added a new OpenFin example: https://github.com/testable/openfin-puppeteer-testable-example. 

It still requires launching OpenFin as a `before` step because we need to be able to control the remote debugging port that OpenFin uses. If we use `browser.launch()` in Puppeteer and we pass a custom remote debugging port it will never connect. Despite that it's still much simpler and lighter weight with Puppeteer because you don't need to install selenium/chromedriver/etc.
